[package]
name = "gpca"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "5.4.0"
image = "0.24.6"
itertools = "0.10.5"
kdam = "0.3.0"
rand = "0.8.5"
rayon = "1.7.0"
tokio = { version="1.28.2", features = ["full"] }


