[package]
name = "gpca"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "5.5.3"
egui-macroquad = "0.12.0"
# fdg-macroquad = "0.3.3"
fdg-sim = "0.9.1"
image = "0.24.7"
itertools = "0.11.0"
kdam = "0.5.0"
macroquad = "0.3"
rand = "0.8.5"
rayon = "1.8.0"
tokio = { version = "1.33.0", features = ["full"] }
