[package]
name = "gpca"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
itertools = "0.10.5"
ndarray = "0.15.6"
ndarray-conv = "0.1.3"
rand = "0.8.5"
